import axios from 'axios';
import { db } from '../infra/db';
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

export class PerplexityService {
  private kbPath: string;

  constructor() {
    const isProd = process.env.NODE_ENV === 'production';
    // Gestione percorsi per trovare i prompt di sistema (Persona Headhunter)
    this.kbPath = isProd 
      ? path.join(process.cwd(), 'dist', 'knowledge_base')
      : path.join(process.cwd(), 'src', 'knowledge_base');
  }

  /**
   * Carica i file di sistema (es. il tono di voce dell'Headhunter o prompt base).
   */
  private loadTextFile(filename: string): string {
    try {
      const possiblePaths = [
        path.join(this.kbPath, filename),
        path.join(this.kbPath, 'developer', filename),
        path.join(process.cwd(), 'src', 'knowledge_base', filename)
      ];

      for (const p of possiblePaths) {
        if (fs.existsSync(p)) return fs.readFileSync(p, 'utf-8');
      }
      return "";
    } catch (e) {
      console.error(`Errore lettura file sistema ${filename}:`, e);
      return "";
    }
  }

  /**
   * --- IL CUORE DINAMICO ---
   * Crea il Prompt di Ricerca leggendo le Keyword generate dall'AI nel profilo utente.
   */
  private generateUserProtocol(profile: any): string {
    // 1. Fallback se il profilo non è configurato
    if (!profile || !profile.dreamRole) {
        return `
        === GENERIC SEARCH PROTOCOL ===
        TARGET: Remote Freelance Opportunities
        CONTEXT: The user has not defined a specific profile yet. Find high-quality remote jobs suitable for a digital nomad.
        `;
    }

    // 2. Estrazione Keyword AI (Create da user.routes.ts)
    const aiData = profile.generatedSearchLogic || {};
    
    // Convertiamo gli array in stringhe pulite per il prompt
    const posKeywords = Array.isArray(aiData.positive_keywords) && aiData.positive_keywords.length > 0
        ? aiData.positive_keywords.join(", ") 
        : (profile.whatToDo || profile.dreamRole); // Fallback manuale

    const negKeywords = Array.isArray(aiData.negative_keywords) && aiData.negative_keywords.length > 0
        ? aiData.negative_keywords.join(", ") 
        : (profile.whatToAvoid || "Scams, MLM"); // Fallback manuale

    // 3. Istruzioni Avanzate Utente
    const extraRules = profile.advancedInstructions || "No extra specific rules.";

    // 4. Costruzione del Manifesto per Perplexity
    return `
    === USER CUSTOM MANIFESTO (AI OPTIMIZED) ===
    
    1. 🎯 TARGET ROLE / NICHE: 
       "${profile.dreamRole}"
    
    2. 🔑 SEARCH KEYWORDS (STRICT PRIORITY):
       Use these exact keywords generated by the AI Analysis:
       
       ✅ MUST INCLUDE (Positive Signals): ${posKeywords}
       ❌ MUST EXCLUDE (Negative Signals): ${negKeywords}

    3. 📝 USER SPECIFIC RULES:
       "${extraRules}"

    4. ⚠️ EXECUTION STRATEGY:
       - Construct search queries combining the Target Role with Positive Keywords.
       - Apply boolean NOT operators (e.g. -${negKeywords.split(', ')[0]}) to filter out the Exclusions.
       - Prioritize results that match the "What to Do" intent implied by the positive keywords.
    ==============================================
    `;
  }

  /**
   * Entry Point: Avvia la ricerca (Daily/Weekly/Monthly).
   */
  public async findGrowthOpportunities(userId: string, clientProfile: any, mode: 'daily' | 'weekly' | 'monthly' = 'daily'): Promise<number> {
    console.log(`\n🚀 [PERPLEXITY] Avvio Caccia ${mode.toUpperCase()} su misura per User: ${userId}`);

    // Genera il protocollo basato sui dati AI salvati
    const userProtocol = this.generateUserProtocol(clientProfile);

    // Determina l'orizzonte temporale
    let recency = 'day';
    if (mode === 'weekly') recency = 'week';
    if (mode === 'monthly') recency = 'month';

    return await this.performSearch(userId, userProtocol, mode, recency);
  }

  /**
   * Esegue la ricerca su Perplexity.
   */
  private async performSearch(userId: string, protocol: string, mode: string, recency: string): Promise<number> {
    
    // Carica la "Persona" dell'Headhunter (comportamento, non contenuto)
    let systemInstructionFile = 'system_headhunter_prompt.md';
    if (mode === 'weekly') systemInstructionFile = 'system_headhunter_weekly.md';
    
    let systemBehavior = this.loadTextFile(systemInstructionFile);
    if (!systemBehavior) systemBehavior = "You are an expert headhunter finding high-value remote gigs.";

    // Costruisce il messaggio finale
    const searchContext = `
      ⚠️ CRITICAL: IGNORE any previous generic instructions. 
      Follow the USER CUSTOM MANIFESTO below strictly.

      ${protocol}

      --- 🎯 SEARCH PARAMETERS ---
      TIMEFRAME: Opportunities published in the last ${recency === 'day' ? '24 HOURS' : '7 DAYS'}.
      LOCATION: Remote (Global/Europe preferred unless User specified otherwise).
      
      YOUR GOAL: Find 5 concrete, active job listings that match the USER MANIFESTO.
      
      OUTPUT FORMAT:
      Return a valid JSON Array. Each object must have:
      - title: Job Title
      - platform: Company or Platform Name
      - hourly_rate: Estimated pay (string)
      - difficulty: "High", "Medium", or "Low"
      - action_link: Direct URL to apply
      - why_it_works: One sentence explaining why this matches the keywords.
    `;

    console.log(`🔍 [QUERY] Esecuzione ricerca con protocollo AI...`);
    
    try {
      const response = await axios.post(
        'https://api.perplexity.ai/chat/completions',
        {
          model: 'sonar-pro', 
          messages: [
            { role: 'system', content: systemBehavior },
            { role: 'user', content: searchContext }
          ],
          temperature: 0.1, // Bassa temperatura per rigore logico
          max_tokens: 4000
        },
        { headers: { 'Authorization': `Bearer ${process.env.PERPLEXITY_API_KEY}` } }
      );

      const rawContent = response.data.choices[0].message.content;
      console.log(`✅ [PERPLEXITY] Risposta ricevuta. Elaborazione...`);
      
      return await this.processAndSaveOpportunities(rawContent, userId, mode as any);

    } catch (error: any) {
      console.error("❌ Errore API Perplexity:", error.response?.data || error.message);
      return 0;
    }
  }

  /**
   * Processa il JSON e salva nel DB (Include FIX Data ISO).
   */
  private async processAndSaveOpportunities(rawContent: string, userId: string, type: 'daily' | 'weekly' | 'monthly'): Promise<number> {
    let opportunities = [];
    
    try {
      // Pulizia del JSON (rimuove i backticks del markdown)
      const jsonStr = rawContent.replace(/```json/g, '').replace(/```/g, '').trim();
      opportunities = JSON.parse(jsonStr);
    } catch (e) {
      console.error("⚠️ Errore parsing JSON da Perplexity.");
      return 0;
    }

    if (!Array.isArray(opportunities) || opportunities.length === 0) {
        console.warn("⚠️ Nessuna opportunità valida trovata.");
        return 0;
    }

    let savedCount = 0;
    
    for (const opp of opportunities) {
      // Verifica duplicati per evitare spam
      const existing = await db.selectFrom('missions')
        .select('id')
        .where('user_id', '=', userId)
        .where((eb) => eb.or([
          eb('source_url', '=', opp.action_link || opp.url),
          eb.and([
            eb('title', '=', opp.title),
            eb('company_name', '=', opp.platform || opp.company)
          ])
        ]))
        .executeTakeFirst();

      if (!existing) {
        await db.insertInto('missions')
          .values({
            id: crypto.randomUUID(),
            user_id: userId,
            title: opp.title,
            company_name: opp.platform || opp.company || "N/A",
            description: `${opp.why_it_works || ''}\n\nRequisiti: ${opp.difficulty || 'N/A'}\n${opp.description || ''}`,
            source_url: opp.action_link || opp.url || "#",
            reward_amount: this.parseReward(opp.hourly_rate || opp.reward),
            estimated_duration_hours: 1, 
            status: 'pending',
            type: type,
            platform: "AI Custom Hunt", // Tagghiamo la provenienza
            match_score: 100,
            // --- FIX CRITICO: Conversione Data per Kysely ---
            created_at: new Date().toISOString() as any, 
            raw_data: JSON.stringify(opp)
          })
          .execute();
        savedCount++;
      }
    }

    console.log(`✅ Salvate ${savedCount} nuove missioni basate su keyword AI.`);
    return savedCount;
  }

  // Helper per estrarre numeri
  private parseReward(rewardStr: string): number {
    if (!rewardStr) return 0;
    const matches = rewardStr.match(/\d+/);
    return matches ? parseInt(matches[0], 10) : 0;
  }
}